### ISSUE TITLE
mkdocs-publisher incompatible with mkdocs 1.6.0?

### ISSUE THREAD

**Issue by ludwikc** [mkdocs-publisher/mkdocs-publisher#90]
### Bug description

`mkdocs-publisher 1.4.0 requires mkdocs<1.6.0,>=1.5.3, but you have mkdocs 1.6.0 which is incompatible.`

### Expected behaviour

Is there anything in  mkdocs 1.6.0 that breaks 1.4.0 version of mkdocs-publisher?

**Comment by mkusz** [comment]
Hi @ludwikc 
Thanks for that. I had some small issue when preparing v1.4.0, but it seems that it shouldn't be a problem to bump it. I will prepare v1.4.1 that will address it in next few days.

PS. Greetings from "Fabryka Kursów" ;)
PS2. If you have some comments and/or suggestions for futures, please lt me know.

**Comment by mkusz** [comment]
Hi @ludwikc ,
It now should be fixed in v1.4.1
