### ISSUE TITLE
mkdocs-publisher adds extra space to Footnotes

### ISSUE THREAD

**Issue by ludwikc** [mkdocs-publisher/mkdocs-publisher#93]
### Bug description

When adding `footnotes` to articles with `mkdocs-publisher` enabled, an extra, unnecessary space is being added. 

This is how it looks with publisher enabled (extra spaces hightlighted)
![SIADLAK-Screenshot-202408111211dkjzg](https://github.com/user-attachments/assets/d3318a50-4e1c-4736-ad45-2c13cf057479)

![SIADLAK-Screenshot-202408111211dlzrm](https://github.com/user-attachments/assets/9878c841-448b-45ec-8225-4d3f2231a6af)

### Expected behaviour

This is how it looks with publisher plugins commented out from `mkdocs.yml`

![SIADLAK-Screenshot-202408111212azuoz](https://github.com/user-attachments/assets/4244a7d7-037a-4f2f-a84e-2deb08b5e2db)

![SIADLAK-Screenshot-202408111212gikei](https://github.com/user-attachments/assets/13dc2494-a951-49a4-a6a6-bf0193c6408c)

**Comment by mkusz** [comment]
Hi @ludwikc,

You have pushed me to finally find the reason for it (I saw it on my pages also). It's also appearing on most links etc. so it's not only on footnotes, but for footnotes it's very visible.

In v1.4.2 it will be fixed.
